### ISSUE TITLE
Cannot continue! Exiting program...

### ISSUE THREAD

**Issue by ilovetwilight** [Mantaro/MantaroBot#150]
[14:30:00] [main] [INFO] [MantaroBot] : Filtering all logs below INFO
[14:30:02] [main] [WARN] [Dsn] : *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/ ***
[14:30:02] [main] [INFO] [DefaultSentryClientFactory] : Using noop to send events.

||        ______ ___  ___            _                 ______       _    ______        ||
||       / / / / |  \/  |           | |                | ___ \     | |   \ \ \ \       ||
||      / / / /  | .  . | __ _ _ __ | |_ __ _ _ __ ___ | |_/ / ___ | |_   \ \ \ \      ||
||     < < < <   | |\/| |/ _` | '_ \| __/ _` | '__/ _ \| ___ \/ _ \| __|   > > > >     ||
||      \ \ \ \  | |  | | (_| | | | | || (_| | | | (_) | |_/ / (_) | |_   / / / /      ||
||       \_\_\_\ \_|  |_/\__,_|_| |_|\__\__,_|_|  \___/\____/ \___/ \__| /_/_/_/       ||

:: MantaroBot 4.8.5 :: Running JDA 3.5.1_339 :: Made by Kodehawa, AdrianTodt & natanbc ::

[14:30:03] [Annotation Lookup (Option)] [INFO] [Reflections] : Reflections took 956 ms to scan 1 urls, producing 7 keys and 19 values 
[14:30:04] [Annotation Lookup (Module)] [INFO] [Reflections] : Reflections took 1448 ms to scan 1 urls, producing 23 keys and 305 values 
[14:30:04] [MantaroCore-ShardInit] [INFO] [ShardedMantaro] : Spawning shards...
[14:30:04] [MantaroCore-ShardInit] [INFO] [ShardedMantaro] : Starting shard #0 of 1
[14:30:07] [redisson-netty-1-1] [INFO] [MasterPubSubConnectionPool] : 1 connections initialized for localhost/127.0.0.1:6379
[14:30:07] [redisson-netty-1-2] [INFO] [MasterConnectionPool] : 10 connections initialized for localhost/127.0.0.1:6379
[14:30:07] [MantaroCore-ShardInit] [INFO] [MantaroData] : Established redis connection to localhost:6379
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at com.rethinkdb.net.Connection$Builder.user(Connection.java:400)
	at net.kodehawa.mantarobot.data.MantaroData.conn(MantaroData.java:58)
	at net.kodehawa.mantarobot.data.MantaroData.db(MantaroData.java:97)
	at net.kodehawa.mantarobot.commands.utils.birthday.BirthdayTask.<init>(BirthdayTask.java:41)
	at net.kodehawa.mantarobot.core.shard.MantaroShard.<init>(MantaroShard.java:73)
	at net.kodehawa.mantarobot.core.shard.ShardedMantaro.shard(ShardedMantaro.java:135)
	at net.kodehawa.mantarobot.core.MantaroCore.lambda$startShardedInstance$0(MantaroCore.java:106)
	at java.lang.Thread.run(Thread.java:748)
[14:30:07] [main] [ERROR] [MantaroBot] : Could not complete Main Thread routine!
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[na:1.8.0_151]
	at java.util.Optional.<init>(Optional.java:96) ~[na:1.8.0_151]
	at java.util.Optional.of(Optional.java:108) ~[na:1.8.0_151]
	at com.rethinkdb.net.Connection$Builder.user(Connection.java:400) ~[MantaroBot-4.8.5.jar:na]
	at net.kodehawa.mantarobot.data.MantaroData.conn(MantaroData.java:58) ~[MantaroBot-4.8.5.jar:na]
	at net.kodehawa.mantarobot.data.MantaroData.db(MantaroData.java:97) ~[MantaroBot-4.8.5.jar:na]
	at net.kodehawa.mantarobot.MantaroBot.<init>(MantaroBot.java:144) ~[MantaroBot-4.8.5.jar:na]
	at net.kodehawa.mantarobot.MantaroBot.main(MantaroBot.java:161) ~[MantaroBot-4.8.5.jar:na]
[14:30:07] [main] [ERROR] [MantaroBot] : Cannot continue! Exiting program...
Help

**Comment by natanbc** [comment]
```
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Optional.(Optional.java:96)
at java.util.Optional.of(Optional.java:108)
at com.rethinkdb.net.Connection$Builder.user(Connection.java:400)
at net.kodehawa.mantarobot.data.MantaroData.conn(MantaroData.java:58)
```

**Comment by Kodehawa** [comment]
in config.json set the rethinkdb user to admin and password to an empty string
