### ISSUE TITLE
zip file closed

### ISSUE THREAD

**Issue by ilovetwilight** [Mantaro/MantaroBot#151]
```java
:: MantaroBot 5.0.0a :: Running JDA 3.5.0_331 :: Made by Kodehawa, AdrianTodt & natanbc ::

[18:47:37] [Annotation Lookup (Option)] [INFO] [Reflections] : Reflections took 1522 ms to scan 1 urls, producing 7 keys and 19 values 
[18:47:37] [MantaroCore-ShardInit] [INFO] [ShardedMantaro] : Spawning shards...
[18:47:37] [MantaroCore-ShardInit] [INFO] [ShardedMantaro] : Starting shard #0 of 1
[18:47:38] [main] [ERROR] [MantaroBot] : Could not complete Main Thread routine!
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: zip file closed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at net.kodehawa.mantarobot.core.MantaroCore.startMainComponents(MantaroCore.java:148)
	at net.kodehawa.mantarobot.MantaroBot.<init>(MantaroBot.java:138)
	at net.kodehawa.mantarobot.MantaroBot.main(MantaroBot.java:167)
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.access$200(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.hasNext(ZipFile.java:508)
	at java.util.zip.ZipFile$ZipEntryIterator.hasMoreElements(ZipFile.java:503)
	at java.util.jar.JarFile$JarEntryIterator.hasNext(JarFile.java:253)
	at java.util.jar.JarFile$JarEntryIterator.hasMoreElements(JarFile.java:262)
	at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:30)
	at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:26)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:140)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:135)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:202)
	at org.reflections.Reflections.<init>(Reflections.java:123)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at net.kodehawa.mantarobot.core.MantaroCore.lambda$lookForAnnotatedOn$3(MantaroCore.java:186)
	at br.com.brjdevs.java.utils.async.threads.CompletableThread.lambda$new$0(CompletableThread.java:20)
	at java.lang.Thread.run(Thread.java:748)
[18:47:38] [main] [ERROR] [MantaroBot] : Cannot continue! Exiting program...
```

**Comment by natanbc** [comment]
Check #152
