### ISSUE TITLE
NoClassDefFoundError lombok

### ISSUE THREAD

**Issue by MacaaGit** [Mantaro/MantaroBot#75]
I am trying to set up the bot (self-host) but its throwing an error 

Exception in thread "main" java.lang.NoClassDefFoundError: lombok/Lombok
        at net.kodehawa.mantarobot.utils.data.GsonDataManager.<init>(GsonDataManager.java:36)
        at net.kodehawa.mantarobot.data.MantaroData.config(MantaroData.java:41)
        at net.kodehawa.mantarobot.services.Carbonitex.<init>(Carbonitex.java:27)
        at net.kodehawa.mantarobot.MantaroBot.<init>(MantaroBot.java:90)
        at net.kodehawa.mantarobot.MantaroBot.main(MantaroBot.java:204)
Caused by: java.lang.ClassNotFoundException: lombok.Lombok
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by natanbc** [comment]
1) Selfbots aren't allowed by discord
2) Mantaro isn't meant to be used as a selfbot

**Comment by MacaaGit** [comment]
Then why in the readme file of Mantaro there is a part which say "Building Mantaro on your own"?

**Comment by natanbc** [comment]
That's about selfhosting, *not* using it as a selfbot

**Comment by MacaaGit** [comment]
Yeah I am sorry I didn't meant Self Bot. But still not working

**Comment by MrLar** [comment]
I'm unsure if you are familiar with the term "self-bot". A "self-bot" is a bot running under a user account only listening to the commands of its owner and no one else. I'm pretty sure you meant self-hosting instead.

**Comment by MacaaGit** [comment]
Yes I meant self-hosting, my bad

**Comment by Kodehawa** [comment]
Nice meme tbh

Natan updated README.md, run gradle shadowJar and try.

**Comment by MacaaGit** [comment]
I am still getting the same error.

**Comment by Kodehawa** [comment]
To be honest, I have no idea because I don't know your setup, but it's something on your side
